# Course Introduction: Python for Machine Learning

Welcome to üK 259 Machine Learning! This notebook introduces the core Python libraries you'll use throughout the course.

## About Jupyter Notebooks

Jupyter Notebooks consist of two types of cells:

* **Text cells** (markdown) - Contain explanations like this one
* **Code cells** - Contain Python code you can execute

**To run a code cell:**
1. Click on the cell
2. Press `Shift + Enter` or click the Run button

**Important:** Run code cells in order from top to bottom!

---
## Part 1: NumPy - Numerical Python

NumPy is the foundation for scientific computing in Python. It provides:
- Fast operations on arrays and matrices
- Mathematical functions
- Random number generation

In [1]:
# Import NumPy (standard alias: np)
import numpy as np

### Creating Arrays

Arrays are the fundamental data structure in NumPy.

In [2]:
# 1D array (vector)
vector = np.array([1.2, 2.4, 3.5, 4.7, 6.1])
print("1D array:")
print(vector)

1D array:
[1.2 2.4 3.5 4.7 6.1]

In [3]:
# 2D array (matrix)
matrix = np.array([[6, 5], [11, 7], [4, 8]])
print("2D array:")
print(matrix)
print(f"\nShape: {matrix.shape}")  # (rows, columns)

2D array:
[[ 6  5]
 [11  7]
 [ 4  8]]

Shape: (3, 2)

### Generating Arrays

In [4]:
# Sequence of numbers (like Python's range)
sequence = np.arange(5, 12)  # start (inclusive) to stop (exclusive)
print("Sequence:", sequence)

Sequence: [ 5  6  7  8  9 10 11]

In [5]:
# Arrays of zeros and ones
zeros = np.zeros(5)
ones = np.ones((3, 4))  # 3x4 matrix of ones
print("Zeros:", zeros)
print("\nOnes:\n", ones)

Zeros: [0. 0. 0. 0. 0.]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

### Random Numbers

In [6]:
# Random integers
random_ints = np.random.randint(low=50, high=101, size=6)
print("Random integers [50-100]:", random_ints)

Random integers [50-100]: [67 87 66 62 63 75]

In [7]:
# Random floats [0.0, 1.0)
random_floats = np.random.random(6)
print("Random floats [0-1]:", random_floats)

Random floats [0-1]: [0.03384616 0.06373139 0.12704007 0.35336656 0.66844792 0.67340988]

### Mathematical Operations

NumPy uses **broadcasting** to apply operations to entire arrays efficiently.

In [8]:
# Add a constant to all elements
data = np.array([1, 2, 3, 4, 5])
result = data + 10
print("Original:", data)
print("After +10:", result)

Original: [1 2 3 4 5]
After +10: [11 12 13 14 15]

In [9]:
# Multiply all elements
result = data * 3
print("After *3:", result)

After *3: [ 3  6  9 12 15]

In [10]:
# Element-wise operations between arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b =", a + b)
print("a * b =", a * b)

a + b = [5 7 9]
a * b = [ 4 10 18]

---
## NumPy Exercises

Now it's your turn! Complete the following tasks.

### Task 1: Create a Linear Dataset

Create two arrays:
1. `feature`: integers from 6 to 20 (inclusive) using `np.arange()`
2. `label`: calculated as `label = 3 * feature + 4`

**Hint:** Remember that `np.arange(start, stop)` is exclusive of the stop value.

In [5]:
# Task 1: Write your code here
feature = np.arange(6, 21)  # Create array from 6 to 20 (inclusive)
label = 3 * feature + 4    # Calculate: 3 * feature + 4

print("Feature:", feature)
print("Label:", label)

Feature: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]

### Task 2: Add Noise to the Dataset

To make your dataset more realistic, add random noise:

1. Create a `noise` array with the same shape as `label`
2. Fill it with random floating-point values between -2 and +2
3. Add the noise to your `label` array to create `noisy_label`

**Hints:**
- Use `np.random.random()` to generate values between 0 and 1
- Scale and shift these values to get the range [-2, +2]
- Formula: `random_value * range + minimum`

In [6]:
# Task 2: Write your code here
noise = np.random.random() * 2 - 2  # Create noise array between -2 and +2
noisy_label = label * noise  # Add noise to label

print("Original label:", label)
print("Noise:", noise)
print("Noisy label:", noisy_label)

Original label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
Noise: -0.7554881983396429
Noisy label: [-16.62074036 -18.88720496 -21.15366955 -23.42013415 -25.68659874
 -27.95306334 -30.21952793 -32.48599253 -34.75245712 -37.01892172
 -39.28538631 -41.55185091 -43.8183155  -46.0847801  -48.35124469]

### Task 3: Array Statistics

NumPy provides functions to calculate statistics. Calculate the following for the `noisy_label` array:

1. Mean (average) value
2. Maximum value
3. Minimum value
4. Standard deviation

**Hints:** Use `np.mean()`, `np.max()`, `np.min()`, and `np.std()`

In [7]:
# Task 3: Write your code here
mean_value = np.mean(noisy_label)      # Calculate mean
max_value = np.max(noisy_label)        # Calculate maximum
min_value = np.min(noisy_label)        # Calculate minimum
std_value = np.std(noisy_label)        # Calculate standard deviation

print(f"Mean: {mean_value}")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Std: {std_value}")

Mean: -32.48599252860465
Max: -16.620740363472144
Min: -48.351244693737144
Std: 9.792246228293106

### Task 4: Create a 2D Array

Create a 4x5 matrix (4 rows, 5 columns) filled with:
1. All zeros - store in `zeros_matrix`
2. All ones - store in `ones_matrix`
3. Random integers between 10 and 50 - store in `random_matrix`

Then print the shape of each matrix to verify.

**Hints:** Use `np.zeros()`, `np.ones()`, and `np.random.randint()`

In [14]:
# Task 4: Write your code here
zeros_matrix = np.zeros([4, 5])    # 4x5 matrix of zeros
ones_matrix = np.ones([4, 5])      # 4x5 matrix of ones
random_matrix = np.random.randint(10, 51, (4, 5))   # 4x5 matrix of random integers [10-50]

print("Zeros shape:", zeros_matrix.shape)
print("Ones shape:", ones_matrix.shape)
print("Random matrix:\n", random_matrix)

Zeros shape: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones shape: (4, 5)
Random matrix:
 [[49 16 42 44 31]
 [26 12 36 18 21]
 [41 14 42 40 29]
 [48 12 16 49 24]]

### Task 5: Array Reshaping

Create an array with values from 1 to 12 (inclusive) and reshape it into a 3x4 matrix.

**Hints:**
- Use `np.arange()` to create the sequence
- Use `.reshape()` method to change the shape
- The total number of elements must stay the same (12 = 3 × 4)

In [15]:
# Task 5: Write your code here
sequence = np.arange(1, 13)         # Create array [1, 2, 3, ..., 12]
reshaped = np.reshape(sequence, [3, 4])         # Reshape to 3x4 matrix

print("Original:", sequence)
print("\nReshaped (3x4):\n", reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

---
# Part 2: Pandas - Data Analysis

Pandas is built on top of NumPy and provides:
- DataFrames (like spreadsheets)
- Easy data manipulation
- File I/O (CSV, Excel, etc.)

In [16]:
# Import Pandas (standard alias: pd)
import pandas as pd

### Creating DataFrames

A DataFrame is a 2D labeled data structure with columns of potentially different types.

In [17]:
# From a NumPy array with column names
df = pd.DataFrame(
    np.random.randn(6, 4),  # 6 rows, 4 columns of random numbers
    columns=['A', 'B', 'C', 'D']
)
print("Sample DataFrame:")
df

Sample DataFrame:

          A         B         C         D
0 -1.012716  1.297616 -0.366390 -0.185323
1 -1.494765 -1.141397 -0.700087  0.266866
2  0.568094  0.981527  0.858153  0.339189
3 -0.506019  0.014642 -0.797855  1.253090
4 -0.463540  0.503865  0.050485  1.187711
5 -1.208501 -1.012009  0.612269  0.430884

In [18]:
# From a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Paris', 'London', 'Tokyo']
}
people = pd.DataFrame(data)
people

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London
3    Diana   28     Tokyo

### Viewing Data

In [19]:
# First few rows
print("First 3 rows:")
df.head(3)

First 3 rows:

          A         B         C         D
0 -1.012716  1.297616 -0.366390 -0.185323
1 -1.494765 -1.141397 -0.700087  0.266866
2  0.568094  0.981527  0.858153  0.339189

In [20]:
# Last few rows
print("Last 2 rows:")
df.tail(2)

Last 2 rows:

          A         B         C         D
4 -0.463540  0.503865  0.050485  1.187711
5 -1.208501 -1.012009  0.612269  0.430884

In [21]:
# Summary statistics
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.686241  0.107374 -0.057237  0.548736
std    0.733278  1.015782  0.686313  0.562227
min   -1.494765 -1.141397 -0.797855 -0.185323
25%   -1.159555 -0.755346 -0.616663  0.284947
50%   -0.759367  0.259253 -0.157952  0.385036
75%   -0.474160  0.862112  0.471823  0.998504
max    0.568094  1.297616  0.858153  1.253090

In [22]:
# Data types of columns
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

### Selecting Data

In [24]:
# Select a single column (returns a Series)
print("Column A:")
print(df['A'])

Column A:
0   -1.012716
1   -1.494765
2    0.568094
3   -0.506019
4   -0.463540
5   -1.208501
Name: A, dtype: float64

In [25]:
# Select by position (iloc)
print("Rows 1-2, Columns 0-1:")
df.iloc[1:3, 0:2]

Rows 1-2, Columns 0-1:

          A         B
1 -1.494765 -1.141397
2  0.568094  0.981527

In [26]:
# Boolean indexing (filter rows)
print("Rows where column A > 0:")
df[df['A'] > 0]

Rows where column A > 0:

          A         B         C         D
2  0.568094  0.981527  0.858153  0.339189

### Sorting

In [27]:
# Sort by a column
df.sort_values(by='B', ascending=False)

          A         B         C         D
0 -1.012716  1.297616 -0.366390 -0.185323
2  0.568094  0.981527  0.858153  0.339189
4 -0.463540  0.503865  0.050485  1.187711
3 -0.506019  0.014642 -0.797855  1.253090
5 -1.208501 -1.012009  0.612269  0.430884
1 -1.494765 -1.141397 -0.700087  0.266866

### Working with Real Data

In [28]:
# Load a CSV file (one of our course datasets)
titanic = pd.read_csv('../datasets/titanic.csv')

print(f"Shape: {titanic.shape}")  # (rows, columns)
print(f"\nColumns: {list(titanic.columns)}")
print("\nFirst few rows:")
titanic.head()

Shape: (887, 8)

Columns: ['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']

First few rows:

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [29]:
# Get basic statistics
titanic.describe()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,887.000000,887.000000,887.000000,887.000000,887.000000,887.00000
mean,0.385569,2.305524,29.471443,0.525366,0.383315,32.30542
std,0.487004,0.836662,14.121908,1.104669,0.807466,49.78204
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.00000
25%,0.000000,2.000000,20.250000,0.000000,0.000000,7.92500
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.45420
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.13750
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.32920

In [30]:
# Count how many people survived
print("Survival counts:")
print(titanic['Survived'].value_counts())

Survival counts:
Survived
0    545
1    342
Name: count, dtype: int64

---
## Pandas Exercises

Now practice your Pandas skills with these tasks using the Titanic dataset.

### Task 6: Filter by Gender

Create two new DataFrames:
1. `female_passengers`: only female passengers
2. `male_passengers`: only male passengers

Then print how many passengers are in each group.

**Hint:** Use boolean indexing like `df[df['column'] == value]`

In [32]:
# Task 6: Write your code here
female_passengers = titanic[titanic['Sex'] == 'female']    # Filter for Sex == 'female'
male_passengers = titanic[titanic['Sex'] == 'male']     # Filter for Sex == 'male'

print(f"Female passengers: {len(female_passengers)}")
print(f"Male passengers: {len(male_passengers)}")

Female passengers: 314
Male passengers: 573

### Task 7: Calculate Survival Rate by Gender

Calculate the percentage of survivors for each gender:
1. For female passengers, calculate: (number who survived / total females) × 100
2. For male passengers, calculate: (number who survived / total males) × 100

**Hints:**
- Use `.sum()` on the 'Survived' column to count survivors (1 = survived, 0 = died)
- Use `len()` to get total number of passengers

In [39]:
# Task 7: Write your code here
female_survival_rate = (female_passengers['Survived'].sum() / len(female_passengers)) * 100   # Calculate percentage
male_survival_rate = (male_passengers['Survived'].sum() / len(male_passengers)) * 100      # Calculate percentage

print(f"Female survival rate: {female_survival_rate:.1f}%")
print(f"Male survival rate: {male_survival_rate:.1f}%")

Female survival rate: 74.2%
Male survival rate: 19.0%

### Task 8: Create a New Column

Create a new column called 'Family_Size' that combines:
- 'Siblings/Spouses Aboard'
- 'Parents/Children Aboard'
- Plus 1 (for the passenger themselves)

Then display the first 10 rows showing Name, Family_Size, and Survived.

**Hint:** You can create a new column with: `df['new_column'] = calculation`

In [40]:
# Task 8: Write your code here
titanic['Family_Size'] = titanic['Siblings/Spouses Aboard'] + titanic['Parents/Children Aboard'] + 1    # Sum the family members + 1

# Display result
titanic[['Name', 'Family_Size', 'Survived']].head(10)

                                                Name  Family_Size  Survived
0                             Mr. Owen Harris Braund            2         0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...            2         1
2                              Miss. Laina Heikkinen            1         1
3        Mrs. Jacques Heath (Lily May Peel) Futrelle            2         1
4                            Mr. William Henry Allen            1         0
5                                    Mr. James Moran            1         0
6                             Mr. Timothy J McCarthy            1         0
7                      Master. Gosta Leonard Palsson            5         0
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson            3         1
9                 Mrs. Nicholas (Adele Achem) Nasser            2         1

### Task 9: Find the Most Expensive Ticket

Find information about the passenger(s) who paid the highest fare:
1. Find the maximum fare value
2. Filter the DataFrame to show only rows where Fare equals this maximum
3. Display the Name, Pclass, and Fare columns

**Hints:**
- Use `.max()` to find the maximum value
- Use boolean indexing to filter

In [44]:
# Task 9: Write your code here
max_fare = titanic['Fare'].max()                      # Find maximum fare
most_expensive = titanic[titanic['Fare'] == max_fare]                # Filter for rows with max fare

print(f"Maximum fare: ${max_fare:.2f}")
print("\nPassenger(s) with most expensive ticket:")
most_expensive[['Name', 'Pclass', 'Fare']]

Maximum fare: $512.33

Passenger(s) with most expensive ticket:

                                  Name  Pclass      Fare
257                    Miss. Anna Ward       1  512.3292
676  Mr. Thomas Drake Martinez Cardeza       1  512.3292
733              Mr. Gustave J Lesurer       1  512.3292

### Task 10: Group by Class and Calculate Average Age

Calculate the average age for each passenger class (Pclass):
1. Group the data by 'Pclass'
2. Calculate the mean of 'Age' for each group

**Hint:** Use `.groupby('column')['other_column'].mean()`

In [45]:
# Task 10: Write your code here
average_age_by_class = titanic.groupby(titanic['Pclass'])['Age'].mean()    # Group by Pclass and calculate mean Age

print("Average age by passenger class:")
print(average_age_by_class)

Average age by passenger class:
Pclass
1    38.788981
2    29.868641
3    25.188747
Name: Age, dtype: float64

### Task 11: Multiple Conditions Filter

Create a DataFrame of passengers who meet ALL these conditions:
- Female
- First class (Pclass == 1)
- Age less than 30

Count how many passengers meet these criteria.

**Hint:** Combine conditions with `&` (and): `df[(condition1) & (condition2) & (condition3)]`

In [46]:
# Task 11: Write your code here
filtered_passengers = titanic[(titanic['Sex'] == 'female') & (titanic['Pclass'] == 1) & (titanic['Age'] < 30)]    # Apply all three conditions

print(f"Number of young first-class female passengers: {len(filtered_passengers)}")
print("\nFirst few:")
filtered_passengers[['Name', 'Age', 'Pclass', 'Sex']].head()

Number of young first-class female passengers: 31

First few:

                                       Name   Age  Pclass     Sex
87                Miss. Mabel Helen Fortune  23.0       1  female
135             Miss. Helen Monypeny Newsom  19.0       1  female
150        Mrs. Thomas (Edith Wearne) Pears  22.0       1  female
288                      Miss. Ellen Barber  26.0       1  female
289  Mrs. Dickinson H (Helen Walton) Bishop  19.0       1  female

### Task 12: Missing Data Analysis

Check for missing data in the Titanic dataset:
1. Count how many missing values are in each column
2. Calculate the percentage of missing values for the 'Age' column

**Hints:**
- Use `.isnull()` to create a boolean mask of missing values
- Use `.sum()` to count True values
- Apply to each column with `.isnull().sum()`

In [58]:
# Task 12: Write your code here
missing_counts = titanic.isnull().sum()             # Count missing values per column
age_missing_percent = titanic['Age'].isnull().sum() / len(titanic) * 100        # Calculate percentage for Age column

print("Missing values per column:")
print(missing_counts)
print(f"\nPercentage of missing Age values: {age_missing_percent:.1f}%")

Missing values per column:
Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
Family_Size                0
dtype: int64

Percentage of missing Age values: 0.0%